### ISSUE TITLE
CAN focus CAN_Start_Military_Industry has incorrect trigger

### ISSUE THREAD

**Issue by Sealeon** [EoaNB-Team/EoaNB#25]
**Description**
The current num_of_available_civilian_factories trigger used in CAN_Start_Military_Industry only works if all constructions have been cancelled or you are deliberately leaving factories idle.

**Branch**
main

**Reproduction**
If applicable, steps to reproduce the behavior:
1. Start one construction as Canada of any type
2. Go to Canadian focus tree
3. Click on "Start Military Industry"
4. Observe that despite having a civilian factory, it says you have none available

**Expected behavior**
CAN_Start_Military_Industry focus should check for factories available for projects using the num_of_civilian_factories_available_for_projects trigger.

**Screenshots**
Before fix:
![image](https://user-images.githubusercontent.com/39866129/221335085-596cb372-f9c0-4d1d-8605-3e8615f30ffc.png)

After fix:
![image](https://user-images.githubusercontent.com/39866129/221335295-4936623f-d836-4fec-b23e-406662c9a3d0.png)

**Notes**
Swap the num_of_available_civilian_factories trigger on line 713 of national focus file "canada_focus.txt" with num_of_civilian_factories_available_for_projects.

**Comment by Sealeon** [comment]
The same issue exists in the Canadian focus CAN_Start_Shipbuilding_Industry where the incorrect trigger is on line 1216 of national focus file "canada_focus.txt"

**Comment by ChrisSGD** [comment]
Fixed, thanks for your input! Feel free to apply as a playtester, we could certainly use the help for the upcoming update.
